	.align 2
voicegroup011:: @ 8677528
	voice_directsound 55, 0, DirectSoundWaveData_gmg_clarinet_55, 240, 0, 255, 127 @ 8677138
	voice_directsound 64, 0, DirectSoundWaveData_gmg_clarinet_64, 240, 0, 255, 127 @ 8677141
	voice_directsound 70, 0, DirectSoundWaveData_gmg_clarinet_70, 240, 0, 255, 127 @ 8677147
	voice_directsound 75, 0, DirectSoundWaveData_gmg_clarinet_75, 240, 0, 255, 127 @ 867714C
	voice_directsound 95, 0, DirectSoundWaveData_gmg_clarinet_95, 240, 0, 255, 127 @ 8677160