	.align 2
voicegroup191:: @ 86B429C
	voice_keysplit_all voicegroup003, @ Percussion
	voice_keysplit voicegroup005, KeySplitTable1  @ Piano 1
	voice_keysplit voicegroup005, KeySplitTable1  @ Piano 1
	voice_keysplit voicegroup005, KeySplitTable1  @ Piano 1
	voice_keysplit voicegroup005, KeySplitTable1  @ Piano 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B42D8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B42E4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B42F0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B42FC
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 235  @ Glockenspiel
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4314
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4320
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B432C
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204  @ Xylophone
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 216  @ Tubular Bell
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4350
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B435C
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127  @ Percussive Organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4374
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188  @ Church Organ Low
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188  @ Church Organ High
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165  @ Accordion
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B43A4
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165  @ Accordion
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 149  @ Nylon String Guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B43C8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B43D4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B43E0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B43EC
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 128, 195, 72, 127  @ Overdrive Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 85, 188, 103, 160  @ Distortion Guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4410
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B441C
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 250, 0, 149  @ Fingered Bass
	voice_noise_alt 60, 0, 0, 0, 2, 7, 0  @ 86B4434
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149  @ Fretless Bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 115  @ Slap Bass
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 206, 127  @ Unused Slap Bass 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 128, 252, 0, 115  @ Synth Bass
	voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass, 255, 178, 180, 165  @ Trinity Mega Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B447C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4488
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4494
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B44A0
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242  @ 86B44AC
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 226, 0, 38  @ Pizzicato Strings
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 204  @ Orchestral Harp
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B44D0
	voice_keysplit voicegroup006, KeySplitTable2  @ String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ String Ensemble
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 86B450C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4518
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204  @ 86B4524
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188  @ 86B4530
	voice_keysplit voicegroup007, KeySplitTable3  @ Trumpet
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 86B4548
	voice_keysplit voicegroup008, KeySplitTable3  @ Tuba
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 86B4560
	voice_keysplit voicegroup009, KeySplitTable5  @ French Horn
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0  @ 86B4578
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0  @ 86B4584
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0  @ 86B4590
	voice_directsound 60, 0, DirectSoundWaveData_rlndgm_altosax, 255, 110, 231, 127  @ Alto Sax
	voice_directsound 60, 0, DirectSoundWaveData_rlndgm_altosax, 255, 110, 231, 127  @ Alto Sax
	voice_directsound 60, 0, DirectSoundWaveData_rlndgm_altosax, 255, 110, 231, 127  @ Alto Sax
	voice_directsound 60, 0, DirectSoundWaveData_rlndgm_altosax, 255, 110, 231, 127  @ Alto Sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B45CC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B45D8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B45E4
	voice_directsound 60, 0, DirectSoundWaveData_rlndgm_clarinet, 240, 0, 231, 127 @ Clarinet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B45FC
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127  @ Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4614
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 0, 255, 204  @ Pan Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B462C
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204  @ Shakuhachi
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127  @ Whistle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4650
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4650
	voice_directsound_no_resample 64, 79, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188  @ 86B4668
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 165, 103, 188  @ 86B4674
	voice_square_2_alt 60, 0, 0, 0, 1, 4, 1  @ Square 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B468C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86B4698
	voice_directsound_no_resample 64, 104, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 86B46A4
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0  @ 86B46B0
	voice_square_2 60, 0, 0, 0, 1, 4, 1  @ 8692648
	
