	.align 2
voicegroup003:: @ 86763D0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_dokidoki, 255, 0, 255, 188  @ Dokidoki 
	voice_directsound 62, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 0  @ Kick Drum
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 180, 175, 228  @ Unused FRLG Snare
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242  @ Acoustic Snare
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127  @ Clap
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242  @ Electric Snare
	voice_directsound 64, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ Low Tom
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 127, 0, 188  @ Close Hi Hat
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0  @ 8676424
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 0, 255, 0  @ 8676430
	voice_directsound_no_resample 64, 34, DirectSoundWaveData_sc88pro_open_low_conga, 255, 0, 255, 0  @ 867643C
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_open_hihat, 255, 242, 141, 0  @ Open Hi Hat
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676454
	voice_directsound 64, 24, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 226  @ Unused High Tom
	voice_directsound_no_resample 33, 89, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ Cymbal Crash 1
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 226 @ Unused High Tom
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676484
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676490
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 867649C
	voice_directsound_no_resample 66, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204  @ Tambourine
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86764B4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86764C0
	voice_directsound_no_resample 33, 89, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188  @ Cymbal Crash 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86764D8
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86764E4
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86764F0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86764FC
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188  @ 8676508
	voice_directsound_no_resample 64, 79, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188  @ 8676514
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 165, 103, 188  @ 8676520
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_sc88pro_jingle_bell, 255, 0, 255, 0  @ 867652C
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676538
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676544
	voice_directsound_no_resample 64, 104, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0  @ 8676550
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0  @ 867655C
	voice_directsound 50, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0  @ 8676568
	voice_directsound 64, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0  @ 8676574
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0  @ 8676580
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 180, 175, 228  @ 867658C
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 0, 255, 242  @ 8676598
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127  @ 86765A4
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242  @ 86765B0
	voice_directsound 64, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 86765BC
	voice_directsound_no_resample 64, 80, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242  @ 86765C8
	voice_directsound 68, 34, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 86765D4
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242  @ 86765E0
	voice_directsound 72, 44, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 86765EC
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 86765F8
	voice_directsound 76, 84, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 8676604
	voice_directsound 80, 94, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226  @ 8676610
	voice_directsound_no_resample 33, 89, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 867661C
	voice_directsound 64, 104, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 235  @ 8676628
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 8676634
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231  @ 8676640
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_dance_drums_ride_bell, 255, 165, 103, 231  @ 867664C

