	.align 2
voicegroup191:: @ 86B429C
	voice_keysplit_all voicegroup003 @ Percussion
	voice_keysplit voicegroup005, KeySplitTable1  @ Piano 1
	voice_directsound 60, 0, DirectSoundWaveData_steinway_b_piano, 255, 252, 0, 239  @ Bright Piano
	voice_keysplit voicegroup001, KeySplitTable4  @ Electric Piano 1
	voice_keysplit voicegroup005, KeySplitTable1  @ Piano 1
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_glockenspiel, 255, 165, 51, 235  @ Glockenspiel
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_xylophone, 255, 235, 0, 204  @ Xylophone
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_tubular_bell, 255, 165, 90, 216  @ Tubular Bell
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2, 255, 0, 255, 127  @ Percussive Organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_low, 255, 76, 154, 188  @ Church Organ Low
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_church_organ3_high, 255, 76, 154, 188  @ Church Organ High
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165  @ Accordion
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_accordion, 255, 0, 255, 165  @ Accordion
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 149  @ Nylon String Guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_overdrive_guitar, 128, 195, 72, 127  @ Overdrive Guitar
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 85, 188, 103, 160  @ Distortion Guitar
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 250, 0, 149  @ Fingered Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149  @ Fretless Bass
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 115  @ Slap Bass
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 206, 127  @ Unused Slap Bass 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_synth_bass, 128, 252, 0, 115  @ Synth Bass
	voice_directsound 60, 0, DirectSoundWaveData_trinity_30303_mega_bass, 255, 178, 180, 165  @ Trinity Mega Bass
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 226, 0, 38  @ Pizzicato Strings
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 0, 204  @ Orchestral Harp
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_keysplit voicegroup006, KeySplitTable2  @ String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ String Ensemble
	voice_keysplit voicegroup006, KeySplitTable2  @ String Ensemble
	voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 128, 165, 128, 188  @ Choir Aahs
	voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 128, 165, 128, 204  @ Female Choir
	voice_directsound 60, 0, DirectSoundWaveData_unused_unknown_male_voice, 128, 165, 128, 188  @ Male Choir
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_keysplit voicegroup007, KeySplitTable3  @ Trumpet
	voice_keysplit voicegroup007, KeySplitTable3  @ Trumpet
	voice_keysplit voicegroup008, KeySplitTable3  @ Tuba
	voice_keysplit voicegroup007, KeySplitTable3  @ Trumpet
	voice_keysplit voicegroup009, KeySplitTable5  @ French Horn
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 48, 0, DirectSoundWaveData_rlndgm_altosax, 255, 110, 231, 127  @ Alto Sax
	voice_directsound 48, 0, DirectSoundWaveData_rlndgm_altosax, 255, 110, 231, 127  @ Alto Sax
	voice_directsound 48, 0, DirectSoundWaveData_rlndgm_altosax, 255, 110, 231, 127  @ Alto Sax 
	voice_directsound 48, 0, DirectSoundWaveData_rlndgm_altosax, 255, 110, 231, 127  @ Alto Sax
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_rlndgm_clarinet, 240, 0, 231, 127 @ Clarinet
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127  @ Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sd90_enhanced_delay_shaku, 255, 0, 255, 204  @ Pan Flute
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 0, 255, 204  @ Shakuhachi
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 255, 0, 255, 127  @ Whistle
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ Square 1
	voice_square_1_alt 60, 0, 0, 1, 0, 2, 6, 1  @ Alt Square 1
	voice_square_2_alt 60, 0, 3, 0, 3, 3, 2  @ Alt Square 2
	voice_square_2_alt 60, 0, 0, 0, 1, 4, 1  @ Square 2
	voice_noise_alt 60, 0, 0, 0, 2, 7, 0  @ Noise
	voice_noise_alt 60, 0, 0, 0, 2, 7, 0  @ Noise
	voice_noise_alt 60, 0, 0, 0, 2, 7, 0  @ Noise
	voice_noise_alt 60, 0, 0, 0, 2, 7, 0  @ Noise
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4830, 0, 7, 15, 2  @ Unidentified Wave 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4840, 0, 7, 15, 2  @ Unidentified Wave Dup 1
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4850, 0, 7, 15, 2  @ Sawtooth Wave
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4860, 0, 7, 15, 2  @ Gen 1 Wave/Sawtooth Wave 2
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4870, 0, 7, 15, 2  @ Unidentified Wave 3
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4880, 0, 7, 15, 2  @ Unidentified Wave 4
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4890, 0, 7, 15, 2  @ Unidentified Wave 5
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B48A0, 0, 7, 15, 2  @ Unidentified Wave 6
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B48B0, 0, 7, 15, 2  @ Sawtooth
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B48C0, 0, 7, 15, 2  @ Saw-Square75 Wave 7
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B48D0, 0, 7, 15, 2  @ Saw-Square75 Wave Dup 7
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B48E0, 0, 7, 15, 2  @ Chipped Square Wave 8
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B48F0, 0, 7, 15, 2  @ Weird Wave 9
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4900, 0, 7, 15, 2  @ Unidentified Wave 10
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4910, 0, 7, 15, 2  @ Triangle Wave 11
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4920, 0, 7, 15, 2  @ Sine-y Wave 12
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_Unused_86B4930, 0, 7, 15, 2  @ Wobble Sawtooth Wave 13
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_Unused_86B4940, 0, 7, 15, 2  @ Smooth Sawtooth Wave 14
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_Unused_86B4950, 0, 7, 15, 2  @ Smooth Sawtooth Wave Dup 14
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_Unused_86B4960, 0, 7, 15, 2  @ Sawtooth Wave
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4970, 0, 7, 15, 2  @ Wobble Saw-Square Wave 15
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4980, 0, 7, 15, 2  @ Thinner Wobble Saw-Square Wave 16
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B4990, 0, 7, 15, 2  @ Noisy Wave 17
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B49A0, 0, 7, 15, 2  @ Weird Wave 18
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_86B49B0, 0, 7, 15, 2  @ Weird Wave 19
