.align 2
voicegroup003:: @ Percussion
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0  @ 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                     @ Instrument Name        Note Key
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_dokidoki, 255, 0, 255, 188                            @ Dokidoki             (35)
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_drum_and_percussion_kick, 255, 0, 255, 0              @ Kick Drum            (36)
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sd90_solo_snare, 255, 180, 175, 228                   @ Unused FRLG Snare    (37)
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_orchestra_snare, 255, 0, 255, 242             @ Acoustic Snare       (38)
	voice_directsound_no_resample 64, 54, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 255, 255, 127           @ Clap                 (39)
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 242                   @ Electric Snare       (40)
	voice_directsound 64, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                @ Low Tom              (41)
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 127, 0, 188                 @ Close Hi Hat         (42)
	voice_directsound 48, 24, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 226                                 @ Unused High Tom      (43)
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 127, 0, 188                 @ Close Hi Hat         (44)
	voice_directsound 64, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                @ Low Tom              (45)
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_open_hihat, 255, 242, 141, 0                  @ Open Hi Hat          (46)
	voice_directsound 70, 24, DirectSoundWaveData_sd90_ambient_tom, 255, 0, 255, 226                                @ Low Tom              (47)
	voice_directsound 64, 24, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 226                                 @ Unused High Tom      (48)
	voice_directsound 63, 104, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231                 @ Cymbal Crash 1       (49)
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_unused_sc55_tom, 255, 0, 255, 226                     @ Unused High Tom      (50)
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_unknown_bell, 255, 231, 0, 188                        @ Unknown Ride Bell    (51)
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188                @ Trinity Cymbal Crash (52)
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_dance_drums_ride_bell, 255, 231, 0, 188               @ Ride Bell            (53)
	voice_directsound_no_resample 66, 34, DirectSoundWaveData_sc88pro_tambourine, 255, 127, 77, 204                 @ Tambourine           (54)
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_trinity_cymbal_crash, 255, 231, 0, 188                @ Trinity Cymbal Crash (55)
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_sd90_cowbell, 255, 231, 0, 188                        @ Cow Bell             (56)
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 235, 0, 231      @ Cymbal Crash 2       (57)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (58*)
	voice_directsound_no_resample 64, 14, DirectSoundWaveData_unknown_bell, 255, 231, 0, 188                        @ Unknown Ride Bell    (59)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (60*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (61*)
	voice_directsound_no_resample 64, 79, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 242, 103, 188           @ Mute High Conga      (62)
	voice_directsound 80, 79, DirectSoundWaveData_sc88pro_mute_high_conga, 255, 242, 103, 188                       @ Open High Conga      (63)
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sc88pro_open_low_conga, 255, 165, 103, 188            @ Open Low Conga       (64)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (65*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (66*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (67*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (68*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (69*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (70*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (71*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (72*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (73*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (74*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (75*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (76*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (77*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (78*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (79*)
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 0                  @ Mute Triangle        (80)
	voice_directsound_no_resample 64, 39, DirectSoundWaveData_sd90_open_triangle, 255, 242, 103, 188                @ Open Triangle        (81)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ Square placeholder   (82*)
	voice_directsound_no_resample 64, 24, DirectSoundWaveData_sc88pro_jingle_bell, 255, 0, 255, 0                   @ Jingle Bells         (83*)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                                         @ ----------Separator for easy viewing------------
	voice_directsound_no_resample 64, 104, DirectSoundWaveData_ethnic_flavours_atarigane, 255, 0, 255, 0            @ Atarigane            (Hold*)
	voice_directsound 63, 64, DirectSoundWaveData_sc88pro_taiko, 255, 0, 255, 0                                     @ Taiko                (Hold*)
	voice_directsound 50, 84, DirectSoundWaveData_ethnic_flavours_kotsuzumi, 255, 0, 255, 0                         @ Kotsuzumi            (Hold*)
	voice_directsound 50, 84, DirectSoundWaveData_ethnic_flavours_ohtsuzumi, 255, 0, 255, 0                         @ Ohtsuzumi            (Hold*)
	voice_directsound 50, 84, DirectSoundWaveData_ethnic_flavours_hyoushigi, 255, 0, 255, 0                         @ Hyoushigi            (Hold*)
	voice_directsound_no_resample 64, 94, DirectSoundWaveData_unused_heart_of_asia_indian_drum, 255, 0, 255, 0      @ Indian Drum          (Hold*)
	voice_directsound_no_resample 24, 64, DirectSoundWaveData_unknown_synth_snare, 255, 180, 175, 228               @ Unknown Synth Snare  (Hold*)  

